### ISSUE TITLE
preact support

### ISSUE THREAD

**Issue by studentIvan** [bitovi/react-to-webcomponent#82]
would be very nice, because react bundle weight too much. Preact has compatible mode, but it falls with this library

**Comment by mediabuff** [comment]
Here is the error message:
react-to-webcomponent.js:4 Uncaught TypeError: Cannot read properties of undefined (reading 'createElement')
    at Object.mount (react-to-webcomponent.js:4:17)
    at [r2wc.render] (core.js:72:70)
    at g.connectedCallback (core.js:62:26)
    at diff-viewer-webc.tsx:155:16
mount @ react-to-webcomponent.js:4
[r2wc.render] @ core.js:72
connectedCallback @ core.js:62
(anonymous) @ diff-viewer-webc.tsx:155

**Comment by mediabuff** [comment]
I use direct from CDN as ESM browser modules. My script includes as follows
` <script type="importmap">
     {
       "imports": {
         "preact/jsx-runtime": "https://cdn.jsdelivr.net/npm/preact-jsx-runtime@1.2.0/+esm",
         "memoize-one": "https://cdn.jsdelivr.net/npm/memoize-one@6.0.0/+esm",
         "emotion":"https://cdn.jsdelivr.net/npm/@emotion/css@11.11.2/+esm",
         "preact": "https://cdn.jsdelivr.net/npm/preact@10.18.1/+esm",
         "prop-types": "https://cdn.jsdelivr.net/npm/prop-types@15.8.1/+esm",
         "classnames": "https://cdn.jsdelivr.net/npm/classnames@2.3.2/+esm",
         "diff": "https://cdn.jsdelivr.net/npm/diff@5.1.0/+esm",

         "@r2wc/react-to-web-component": "https://cdn.jsdelivr.net/npm/react-to-webcomponent@2.0.0/+esm"

       }
     }
 </script>`
